name: TestNG-Product-Tests
on: [push]

jobs:
  build_test:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 22
      uses: actions/setup-java@v3
      with:
        java-version: '22'
        distribution: 'temurin'
        cache: maven
    - name: Build with Maven
      run: mvn test
    - uses: actions/upload-artifact@v4
      with:
        name: extent-report
        path: test-output/extent.html
        retention-days: 30
